# Generated by Django 5.1.6 on 2025-02-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('cancer_stage', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('blood_pressure', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
