# Generated by Django 5.1.6 on 2025-02-26 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_patient_index_patient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='index',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=60)),
                ('completed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='queue_app.patient')),
            ],
            options={
                'ordering': ['appointment_time'],
            },
        ),
    ]
